name: bosscubes2
description: "A new Flutter project."


publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  intl: ^0.19.0
  logger: ^2.2.0
  url_launcher: ^6.2.6
  flutter_native_splash: ^2.4.0
  google_nav_bar: ^5.0.6
  get: ^4.6.6
  rxdart: ^0.27.7
  flutter_neat_and_clean_calendar: ^0.3.16+36
  google_fonts: ^6.2.1
  equatable: ^2.0.5
  flex_color_scheme: ^7.3.1
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  gap: ^3.0.1
  go_router: ^14.1.1
  path: ^1.9.0
  sqflite: ^2.3.3+1
  provider: ^6.0.0
  animated_toggle_switch: ^0.8.2
  dropdown_button2: ^2.3.9


 
  cupertino_icons: ^1.0.6
  iconsax: ^0.0.8

  
  flutter_lints: ^3.0.0


flutter:

  
  uses-material-design: true

  
  assets:
    - assets/logos/BossCubess.png
    - assets/logos/mail.png
    - assets/logos/check_mark.png
    - assets/logos/no_events.png
    - assets/logos/pp.png
    - assets/logos/profile-background.png
    - assets/logos/pp2.png
    - assets/logos/task.png
    

  
# fonts:
#   - family: Poppins
#      fonts:
#        - asset: fonts/Poppins-Regular.ttf
#            weight:400
#        - asset: fonts/Poppins-Light.ttf
#            weight:300
#        - asset: fonts/Poppins-Italic.ttf
#            style: italic
#        - asset: fonts/Poppins-Medium.ttf
#            weight:500

#     - family: Trajan Pro
#       fonts:
#         - asset: fonts/TrajanPro.ttf
#         - asset: fonts/TrajanPro_Bold.ttf
#         - weight: 700
  
  